/**
 Auto-generated by: angular-three-plugin:gltf
 Size: C:\Users\timz_\Desktop\Projects\angular-learn\public\models\Male.gltf [579.1KB] &gt; C:\Users\timz_\Desktop\Projects\angular-learn\public\models\Male.gltf-transformed.glb [164.5KB] (72%)
 */

import type * as THREE from 'three';
import { Group, SkinnedMesh } from 'three';
import {
  extend,
  type NgtThreeElements,
  NgtElementEvents,
  NgtObjectEvents,
  NgtArgs,
} from 'angular-three';
import {
  Component,
  ChangeDetectionStrategy,
  CUSTOM_ELEMENTS_SCHEMA,
  input,
  viewChild,
  ElementRef,
  inject,
  effect,
  model,
} from '@angular/core';
import { gltfResource } from 'angular-three-soba/loaders';
import type { GLTF } from 'three-stdlib';
import {
  animations,
  type NgtsAnimationClips,
  type NgtsAnimationApi,
} from 'angular-three-soba/misc';

// @ts-expect-error - import .glb/.gltf file
import CharacterGLTF from '../../../../../../public/models/Male.gltf-transformed.glb' with { loader: 'file' };

gltfResource.preload(CharacterGLTF);

type ActionName = 'Idle' | 'Run';
type CharacterAnimationClips = NgtsAnimationClips<ActionName>;
export type CharacterAnimationApi = Exclude<
  NgtsAnimationApi<CharacterAnimationClips>,
  { get isReady(): false }
>;

export type CharacterGLTFGLTFResult = GLTF & {
  nodes: {
    characterMedium: THREE.SkinnedMesh;
    LeftFootCtrl: THREE.Bone;
    RightFootCtrl: THREE.Bone;
    HipsCtrl: THREE.Bone;
  };
  materials: {
    'skin.001': THREE.MeshStandardMaterial;
  };
  animations: CharacterAnimationClips[];
};

@Component({
  selector: 'game-character',
  template: `
    @if (gltf.value(); as gltf) {
      @let nodes = gltf.nodes;
      @let materials = gltf.materials;

      <ngt-group #model [parameters]="options()" [dispose]="null">
        <ngt-group name="Root003" [scale]="0.64">
          <ngt-primitive *args="[nodes.LeftFootCtrl]" />
          <ngt-primitive *args="[nodes.RightFootCtrl]" />
          <ngt-primitive *args="[nodes.HipsCtrl]" />
          <ngt-skinned-mesh
            name="characterMedium"
            [geometry]="nodes.characterMedium.geometry"
            [material]="materials['skin.001']"
            [skeleton]="nodes.characterMedium.skeleton"
          />
        </ngt-group>

        <ng-content />
      </ngt-group>
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: NgtObjectEvents,
      outputs: [
        'click',
        'dblclick',
        'contextmenu',
        'pointerup',
        'pointerdown',
        'pointerover',
        'pointerout',
        'pointerenter',
        'pointerleave',
        'pointermove',
        'pointermissed',
        'pointercancel',
        'wheel',
      ],
    },
    {
      directive: NgtElementEvents,
      outputs: ['attached', 'updated', 'created', 'disposed'],
    },
  ],
  imports: [NgtArgs],
})
export class Character {
  protected readonly Math = Math;
  characterState = input<ActionName>('Idle');
  options = input({} as Partial<NgtThreeElements['ngt-group']>);
  animations = model<CharacterAnimationApi>();

  modelRef = viewChild<ElementRef<Group>>('model');

  protected gltf = gltfResource<CharacterGLTFGLTFResult>(() => CharacterGLTF, {
    useDraco: true,
  });

  constructor() {
    extend({ Group, SkinnedMesh });

    const _animations = animations(this.gltf.value, this.modelRef);
    effect(() => {
      if (!_animations.isReady) return;
      this.animations.set(_animations);
    });

    const objectEvents = inject(NgtObjectEvents, { host: true });
    const elementEvents = inject(NgtElementEvents, { host: true });

    objectEvents.ngtObjectEvents.set(this.modelRef);
    elementEvents.ngtElementEvents.set(this.modelRef);

    effect((onCleanup) => {
      const [animations, characterState] = [
        this.animations(),
        this.characterState(),
      ];
      if (!animations) return;
      animations.actions[characterState].reset().fadeIn(0.2).play();
      onCleanup(() => {
        animations.actions[characterState].fadeOut(0.2);
      });
    });
  }
}
