/**
 Auto-generated by: angular-three-plugin:gltf
 Size: C:\Users\timz_\Desktop\Projects\angular-learn\public\models\Stage.gltf [3.54MB] &gt; C:\Users\timz_\Desktop\Projects\angular-learn\public\models\Stage.gltf-transformed.glb [1.17MB] (67%)
 */

import type * as THREE from 'three';
import { Group, Mesh } from 'three';
import {
  extend,
  type NgtThreeElements,
  NgtElementEvents,
  NgtObjectEvents,
} from 'angular-three';
import {
  Component,
  ChangeDetectionStrategy,
  CUSTOM_ELEMENTS_SCHEMA,
  input,
  viewChild,
  ElementRef,
  inject,
} from '@angular/core';
import { gltfResource } from 'angular-three-soba/loaders';
import type { GLTF } from 'three-stdlib';

// @ts-expect-error - import .glb/.gltf file
import StageGLTF from '../../../../../../public/models/Stage.gltf-transformed.glb' with { loader: 'file' };

gltfResource.preload(StageGLTF);

export type StageGLTFGLTFResult = GLTF & {
  nodes: {
    Torii: THREE.Mesh;
    wheels_detals: THREE.Mesh;
    hill_01: THREE.Mesh;
    body: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    '': THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshPhysicalMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
  };
};

@Component({
  selector: 'game-stage',
  template: `
    @if (gltf.value(); as gltf) {
      @let nodes = gltf.nodes;
      @let materials = gltf.materials;

      <ngt-group #model [parameters]="options()" [dispose]="null">
        <ngt-mesh
          [geometry]="nodes.Torii.geometry"
          [material]="materials.PaletteMaterial001"
          [position]="[0, 3.348, -11.608]"
          [rotation]="[Math.PI, -0.822, Math.PI]"
          [scale]="15.555"
        />
        <ngt-mesh
          [geometry]="nodes.wheels_detals.geometry"
          [material]="nodes.wheels_detals.material"
          [position]="[7.861, 0.41, -5.581]"
        />
        <ngt-mesh
          [geometry]="nodes.hill_01.geometry"
          [material]="materials.PaletteMaterial003"
          [position]="[0.117, 1.595, -18.891]"
          [rotation]="[0, -0.139, 0]"
          [scale]="[2.394, 1.763, 1.417]"
        />
        <ngt-mesh
          [geometry]="nodes.body.geometry"
          [material]="materials.PaletteMaterial002"
          [position]="[-10.213, 0, -7.059]"
          [rotation]="[0, 0.619, 0]"
          [scale]="0.401"
        />

        <ng-content />
      </ngt-group>
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: NgtObjectEvents,
      outputs: [
        'click',
        'dblclick',
        'contextmenu',
        'pointerup',
        'pointerdown',
        'pointerover',
        'pointerout',
        'pointerenter',
        'pointerleave',
        'pointermove',
        'pointermissed',
        'pointercancel',
        'wheel',
      ],
    },
    {
      directive: NgtElementEvents,
      outputs: ['attached', 'updated', 'created', 'disposed'],
    },
  ],
})
export class Stage {
  protected readonly Math = Math;

  options = input({} as Partial<NgtThreeElements['ngt-group']>);

  modelRef = viewChild<ElementRef<Group>>('model');

  protected gltf = gltfResource<StageGLTFGLTFResult>(() => StageGLTF, {
    useDraco: true,
  });

  constructor() {
    extend({ Group, Mesh });

    const objectEvents = inject(NgtObjectEvents, { host: true });
    const elementEvents = inject(NgtElementEvents, { host: true });

    objectEvents.ngtObjectEvents.set(this.modelRef);
    elementEvents.ngtElementEvents.set(this.modelRef);
  }
}
