/**
 Auto-generated by: angular-three-plugin:gltf
 Size: C:\Users\tim.zimmermann\Desktop\learning\angular-learn\public\models\Torii.glb [50.09KB] &gt; C:\Users\tim.zimmermann\Desktop\learning\angular-learn\public\models\Torii.glb-transformed.glb [4.99KB] (90%)
 */

import type * as THREE from 'three';
import { Group, Mesh } from 'three';
import {
  extend,
  type NgtThreeElements,
  NgtElementEvents,
  NgtObjectEvents,
} from 'angular-three';
import {
  Component,
  ChangeDetectionStrategy,
  CUSTOM_ELEMENTS_SCHEMA,
  input,
  viewChild,
  ElementRef,
  inject,
} from '@angular/core';
import { gltfResource } from 'angular-three-soba/loaders';
import type { GLTF } from 'three-stdlib';

// @ts-expect-error - import .glb/.gltf file
import ToriiGLTF from '../../../../../../public/models/Torii.glb-transformed.glb' with { loader: 'file' };

gltfResource.preload(ToriiGLTF);

export type ToriiGLTFGLTFResult = GLTF & {
  nodes: {
    'Node-Mesh': THREE.Mesh;
    'Node-Mesh_1': THREE.Mesh;
  };
  materials: {
    mat23: THREE.MeshStandardMaterial;
    mat14: THREE.MeshStandardMaterial;
  };
};

@Component({
  selector: 'game-torii',
  template: `
    @if (gltf.value(); as gltf) {
      @let nodes = gltf.nodes;
      @let materials = gltf.materials;

      <ngt-group #model [parameters]="options()" [dispose]="null">
        <ngt-mesh
          [geometry]="nodes['Node-Mesh'].geometry"
          [material]="materials.mat23"
        />
        <ngt-mesh
          [geometry]="nodes['Node-Mesh_1'].geometry"
          [material]="materials.mat14"
        />

        <ng-content />
      </ngt-group>
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: NgtObjectEvents,
      outputs: [
        'click',
        'dblclick',
        'contextmenu',
        'pointerup',
        'pointerdown',
        'pointerover',
        'pointerout',
        'pointerenter',
        'pointerleave',
        'pointermove',
        'pointermissed',
        'pointercancel',
        'wheel',
      ],
    },
    {
      directive: NgtElementEvents,
      outputs: ['attached', 'updated', 'created', 'disposed'],
    },
  ],
})
export class Torii {
  protected readonly Math = Math;

  options = input({} as Partial<NgtThreeElements['ngt-group']>);

  modelRef = viewChild<ElementRef<Group>>('model');

  protected gltf = gltfResource<ToriiGLTFGLTFResult>(() => ToriiGLTF, {
    useDraco: true,
  });

  constructor() {
    extend({ Group, Mesh });

    const objectEvents = inject(NgtObjectEvents, { host: true });
    const elementEvents = inject(NgtElementEvents, { host: true });

    objectEvents.ngtObjectEvents.set(this.modelRef);
    elementEvents.ngtElementEvents.set(this.modelRef);
  }
}
