/**
 Auto-generated by: angular-three-plugin:gltf
 Size: C:\Users\tim.zimmermann\Desktop\learning\angular-learn\public\MushroomKing.gltf [1.22MB] &gt; C:\Users\tim.zimmermann\Desktop\learning\angular-learn\public\MushroomKing.gltf-transformed.glb [330.35KB] (73%)
 */

import type * as THREE from 'three';
import { Group, SkinnedMesh } from 'three';
import { extend, type NgtThreeElements, NgtElementEvents, NgtObjectEvents, NgtArgs  } from 'angular-three';
import { Component, ChangeDetectionStrategy, CUSTOM_ELEMENTS_SCHEMA, input, viewChild, ElementRef, inject, effect, model, signal } from '@angular/core';
import { gltfResource } from 'angular-three-soba/loaders';
import type { GLTF } from 'three-stdlib';
import { animations, type NgtsAnimationClips, type NgtsAnimationApi } from 'angular-three-soba/misc';

// @ts-expect-error - import .glb/.gltf file
import MushroomKingGLTF from '../../../../public/MushroomKing.gltf-transformed.glb' with { loader: 'file' };
import { modelHoveredAnimation } from '../model-hovered-animation';


gltfResource.preload(MushroomKingGLTF);


type ActionName = 'Death' | 'Duck' | 'HitReact' | 'Idle' | 'Jump' | 'Jump_Idle' | 'Jump_Land' | 'No' | 'Punch' | 'Run' | 'Walk' | 'Wave' | 'Weapon' | 'Yes';
type MushroomKingAnimationClips = NgtsAnimationClips<ActionName>;
export type MushroomKingAnimationApi = Exclude<NgtsAnimationApi<MushroomKingAnimationClips>, { get isReady(): false }>;

export type MushroomKingGLTFGLTFResult = GLTF & {
  nodes: {
    'Mushroom': THREE.SkinnedMesh;
'MushroomKing': THREE.SkinnedMesh
    'Root': THREE.Bone
  };
  materials: {
    'Atlas': THREE.MeshStandardMaterial
  };
  animations: MushroomKingAnimationClips[];
};

@Component({
  selector: 'app-mushroom-king',
  template: `
    @if (gltf.value(); as gltf) {
      @let nodes = gltf.nodes;
      @let materials = gltf.materials;

      <ngt-group #model [parameters]="options()" (pointerover)="hovered.set(true)" (pointerout)="hovered.set(false)">
        <ngt-primitive *args=[nodes.Root] />

<ngt-skinned-mesh name="Mushroom" [geometry]="nodes.Mushroom.geometry" [material]="materials.Atlas" [skeleton]="nodes.Mushroom.skeleton" />
<ngt-skinned-mesh name="MushroomKing" [geometry]="nodes.MushroomKing.geometry" [material]="materials.Atlas" [skeleton]="nodes.MushroomKing.skeleton" />

        <ng-content />
      </ngt-group>
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: NgtObjectEvents,
      outputs: ['click', 'dblclick', 'contextmenu', 'pointerup', 'pointerdown', 'pointerover', 'pointerout', 'pointerenter', 'pointerleave', 'pointermove', 'pointermissed', 'pointercancel', 'wheel'],
    },
    {
      directive: NgtElementEvents,
      outputs: ['attached', 'updated', 'created', 'disposed']
    }
  ],
  imports: [NgtArgs]
})
export class MushroomKing {
  protected readonly Math = Math;

  options = input({} as Partial<NgtThreeElements['ngt-group']>);
  animations = model<MushroomKingAnimationApi>();

  modelRef = viewChild<ElementRef<Group>>('model');

  protected gltf = gltfResource<MushroomKingGLTFGLTFResult>(() =>  MushroomKingGLTF , { useDraco: true });

  protected hovered = signal(false);

  constructor() {
    extend({ Group, SkinnedMesh });

    
    const _animations = animations(this.gltf.value, this.modelRef);
    effect(() => {
      if (!_animations.isReady) return;
      this.animations.set(_animations);
    });
    
    modelHoveredAnimation(
      this.hovered,
      this.animations,
      "Walk",
      "Run"
    )

    const objectEvents = inject(NgtObjectEvents, { host: true });
    const elementEvents = inject(NgtElementEvents, { host: true });

    objectEvents.ngtObjectEvents.set(this.modelRef);
    elementEvents.ngtElementEvents.set(this.modelRef);
  }
}
